name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # GitHub offers Python 3.10

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      # Run pylint
      - name: Run pylint
        continue-on-error: true  # Allow workflow to proceed even if pylint fails
        run: |
          pylint privacy_protection.py || echo "Pylint did not return 10/10"

      # Run pytest
      - name: Run tests
        run: |
          export PYTHONPATH=$(pwd)
          pytest tests/
